# Generated by Django 5.1.4 on 2026-07-01 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("export", "Export des données (Art. 15 & 20)")],
                        default="export",
                        max_length=20,
                        verbose_name="Type de demande",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        blank=True, help_text="Format du fichier remis (json, csv).", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçue"),
                            ("in_progress", "En cours"),
                            ("completed", "Répondue"),
                            ("failed", "Échec"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Reçue le")),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Répondue le"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, verbose_name="Fichier")),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="Empreinte SHA-256 du fichier exporté (preuve d'intégrité).",
                        max_length=64,
                        verbose_name="Empreinte SHA-256",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur à l'origine de la demande. Conservé à null si le compte est supprimé, afin de garder la trace d'audit sans donnée personnelle.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande RGPD",
                "verbose_name_plural": "Demandes RGPD (audit)",
                "ordering": ["-created_at"],
            },
        ),
    ]
